# Generated by Django 5.0.6 on 2024-05-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0003_class_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday'), ('CN', 'Sunday')], max_length=2, null=True, verbose_name='Day of the Week'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='oopsdance.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
