# Generated by Django 5.0.6 on 2024-05-18 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0004_classschedule_day_of_the_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday'), ('CN', 'Sunday')], default='2', max_length=2, verbose_name='Day of the Week'),
        ),
    ]
