# Generated by Django 5.0.6 on 2024-05-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0005_remove_classschedule_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='oopsdance.class', verbose_name='Class'),
        ),
    ]
