# Generated by Django 5.0.6 on 2024-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0008_remove_class_schedules_alter_classschedule_class_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='oopsdance.classschedule', verbose_name='Lịch học'),
        ),
    ]
