# Generated by Django 5.0.6 on 2024-05-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0020_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('student', 'Student'), ('staff', 'Staff')], max_length=10),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_value_room1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_room1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_room1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_value_room2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_room2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_room2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
