# Generated by Django 5.0.6 on 2024-05-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0021_alter_user_role_revenue_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rental_details', models.CharField(max_length=255)),
                ('payment_method', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=100)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
