# Generated by Django 5.0.6 on 2024-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0022_fixedrental'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('Week 1', 'Week 1'), ('Week 2', 'Week 2'), ('Week 3', 'Week 3'), ('Week 4', 'Week 4'), ('Week 5', 'Week 5')], max_length=10)),
                ('time_slot', models.TimeField()),
                ('monday_date', models.DateField(blank=True, null=True)),
                ('tuesday_date', models.DateField(blank=True, null=True)),
                ('wednesday_date', models.DateField(blank=True, null=True)),
                ('thursday_date', models.DateField(blank=True, null=True)),
                ('friday_date', models.DateField(blank=True, null=True)),
                ('saturday_date', models.DateField(blank=True, null=True)),
                ('sunday_date', models.DateField(blank=True, null=True)),
                ('monday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('monday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('tuesday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('tuesday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('wednesday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('wednesday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('thursday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('thursday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('friday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('friday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('saturday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('saturday_room2_booking', models.CharField(blank=True, max_length=255)),
                ('sunday_room1_booking', models.CharField(blank=True, max_length=255)),
                ('sunday_room2_booking', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
