# Generated by Django 5.0.6 on 2024-05-20 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0023_weeklyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(verbose_name='Ngày check-in')),
                ('checkout_date', models.DateTimeField(verbose_name='Ngày check-out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.room', verbose_name='Phòng')),
            ],
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_type', models.CharField(max_length=50, verbose_name='Loại khách hàng')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.booking', verbose_name='Đặt chỗ')),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Tên trạng thái')),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
        migrations.AddField(
            model_name='revenue',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oopsdance.booking', verbose_name='Đặt chỗ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.bookingstatus', verbose_name='Trạng thái đặt chỗ'),
        ),
        migrations.AlterField(
            model_name='fixedrental',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.bookingstatus', verbose_name='Trạng thái đặt chỗ'),
        ),
    ]
