# Generated by Django 5.0.6 on 2024-05-20 17:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0024_booking_bookingguest_bookingstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Thời gian check-in'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Thời gian check-out'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày'),
        ),
    ]
