# Generated by Django 5.0.6 on 2024-05-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0025_remove_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oopsdance.room', verbose_name='Phòng'),
        ),
    ]
