# Generated by Django 5.0.6 on 2024-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0027_alter_classschedule_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('student', 'Student'), ('staff', 'Staff'), ('guest', 'Guest')], max_length=10),
        ),
    ]
