# Generated by Django 5.0.6 on 2024-05-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0029_alter_booking_guest_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('checkin_time', models.TimeField(verbose_name='Checkin Time')),
                ('checkout_time', models.TimeField(verbose_name='Checkout Time')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('canceled', 'Canceled')], max_length=20, verbose_name='Status')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.class', verbose_name='Class')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oopsdance.room', verbose_name='Room')),
            ],
        ),
    ]
