# Generated by Django 5.0.6 on 2024-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0030_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=10, verbose_name='Day of the Week'),
        ),
    ]
