# Generated by Django 5.0.6 on 2024-06-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0031_alter_classschedule_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Checkin Time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Checkout Time'),
        ),
    ]
