# Generated by Django 5.0.6 on 2024-06-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0035_booking_bank_transfer_booking_cash_booking_deposited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deposited',
            new_name='deposite',
        ),
        migrations.AddField(
            model_name='booking',
            name='deposite_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=10, verbose_name='Trạng thái đặt cọc'),
        ),
    ]
