# Generated by Django 5.0.6 on 2024-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0036_rename_deposited_booking_deposite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá phòng'),
            preserve_default=False,
        ),
    ]
