# Generated by Django 5.0.6 on 2024-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0037_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('staff', 'Staff'), ('guest', 'Guest')], max_length=10),
        ),
    ]
