# Generated by Django 5.0.6 on 2024-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0039_classstudent_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_lesson',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
