# Generated by Django 5.0.6 on 2024-06-07 09:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0042_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
