# Generated by Django 5.0.6 on 2024-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0043_attendance_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deposite',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='deposite_status',
            new_name='deposit_status',
        ),
    ]
