# Generated by Django 5.0.6 on 2024-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0044_rename_deposite_booking_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết'),
        ),
    ]
