# Generated by Django 5.0.6 on 2024-06-17 14:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0045_attendance_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='proof',
            new_name='checkin_proof',
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
