# Generated by Django 5.0.6 on 2024-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oopsdance', '0047_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng tiền phải trả'),
        ),
        migrations.AddField(
            model_name='booking',
            name='real_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số tiền thực thu'),
        ),
    ]
